### ISSUE TITLE
Create an interface for Kinds

### ISSUE THREAD

**Issue by nc-wittj** [JosiahWitt/erk#15]
Currently `erk.Kind` is an empty interface, meaning we get no type checking. Let's add a method to that interface, which would be implemented on `erk.DefaultKind`. That switch would require creating kinds like (and would be a breaking change):

```
type ErkMyKind struct { erk.DefaultKind }
```

Using struct embedding is useful for other things, like HTTP statuses, or any other metadata you want to attach to the kind (like marking certain kinds as warnings).

**Comment by JosiahWitt** [comment]
Fixed by #16
